site_name: "gsxform: "
site_url: https://armaank.github.io/gsxform

docs_dir: docs/

theme:
  name: material
  icon:
    logo: "fontawesome/solid/book"
  features:
    - instant
    - tabs
  language: en
nav:
  - Home: index.md
  - API Reference:
    - Graph Utilities: graph.md

extra_css:
    - css/custom.css
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc
repo_name: "armaank/gsxform"
repo_url: "https://github.com/armaank/gsxform"
