site_name: "gsxform: Wavelet scattering transforms on graphs"
site_url: https://armaank.github.io/gsxform

docs_dir: docs/

theme:
  name: material
  icon:
    logo: fontawesome/solid/book
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
      #- navigation.tabs
    - toc.integrate
  language: en

nav:
  - Home: index.md
  - API Reference:
    - Graph utilities: graph.md
    - Wavelet utilities:
        Kernel functions: kernel.md
        Graph wavelet transforms: wavelets.md

extra_css:
    - css/custom.css
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc
repo_name: armaank/gsxform
repo_url: https://github.com/armaank/gsxform

