name: tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v1
      - name: Setup env
        shell: bash -l {0}
        run: |
          echo "Setting up conda environment..."
          make conda
          echo "Setting up development environment..."
          export BASE_CONDA=`conda info --base`
          source $BASE_CONDA/etc/profile.d/conda.sh
          source scripts/setup.sh
          echo "Set up sucessfull"  
      - name: run tests
        shell: bash -l {0}
        run: |
          echo "starting tests..."
          make tests
      - name: compute and upload codecov
        uses: codecov/codecov-action@v1
        with:
           token: ${{ secrets.CODECOV_TOKEN }}
           file: ./coverage.xml
           name: codecov-umbrella
           fail_ci_if_error: true

           # add additional configs here for make test, code cov computation
