name: tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v1
      - name: Setup env
        run: echo "Setting up conda environment..."
        run: make conda
        run: echo "Setting up development environment..."
        run: make setup
      - run: echo "Set up sucessfull"  
# add additional configs here for make test, code cov computation
